project:
  type: website
  output-dir: docs

website:
  title: "Nazmul Alam, PhD"
  page-navigation: true

# Page footer
  page-footer: 
    border: true
    background: dark
    
    left: "Copyright 2024, Nazmul Alam, PhD" 
    right: 
      - icon: linkedin
        href: https://linkedin.com/in/nazmul-alam/

# Top Navigation bar
  navbar:
    background: dark
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "HPLC"
        href: hplc/intro.qmd
      - text: "MassSpec"
        href: mass/intro.qmd
    right: 
      - icon: envelope
        href: mailto:nazmulche@gmail.com
      - icon: linkedin
        href: https://linkedin.com/in/nazmul-alam/

# Left sidebar

  sidebar:
    - title: "HPLC"
      style: "docked"
      search: true
      background: dark
      contents: 
        - href: hplc/intro.qmd
        - section: "Chapters"
          #href: hplc/ch-1.qmd
          contents:
            - hplc/ch-1.qmd
            - hplc/ch-2.qmd
    - title: "MassSpec"
      contents:
        - mass/intro.qmd
        - section: "Mass Spec-101"
          #href: mass/ch-1.qmd
          contents:
            - mass/1-introduction.qmd
            - mass/2-mass-spectra.qmd
            - mass/3-parameters.qmd
            - mass/4-challenges.qmd
            - mass/5-types-of-ms.qmd
            - mass/6-solutions.qmd
            - mass/7-summary.qmd
    - title: "Mass Spec."
      contents:
        - href: mass/intro.qmd
        - section: "Mass Chapters"
          #href: mass/ch-1.qmd
          contents:
            - mass/ch-1.qmd
            - mass/ch-2.qmd
            - mass/ch-3.qmd
            
      
# Formate
format:
  html:
    theme: cosmo
    css: styles.css
